# Generated by Django 6.0.2 on 2026-02-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
