# Generated by Django 6.0.2 on 2026-02-22 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplaces", "0002_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productoffer",
            name="url",
        ),
    ]
